#!/bin/bash

set -e

# - Env
ROOT_DIR=${ROOT_DIR?"ERROR: Required environment variable not set."}
CURR_DIR=$(cd $(dirname $0) && pwd)
source $ROOT_DIR/.env.config
source $ROOT_DIR/.env.credentials

# - Config
VAR_LIST_FILE_PATH="$ROOT_DIR/terraform/variables.tf"
VAR_GET_DIR_PATH="$CURR_DIR/get.sh.d"
ENV_OUT="$ROOT_DIR/.env.autogen.tf-var"

# - List
function list() {
    local REGEX='^variable "([A-Z_]+)" {$'
    cat $VAR_LIST_FILE_PATH \
        | grep -E "$REGEX" \
        | sed -E "s/$REGEX/\1/g"
}

# - Get
function get() {
    local name=$1
    if [[ -f $VAR_GET_DIR_PATH/$name.sh ]]; then
        $VAR_GET_DIR_PATH/$name.sh
    else
        printenv $name \
            || (echo "ERROR: Required environment variable not set." 1>&2; exit 1)
    fi
}

# - Generate
cat << EOF > $ENV_OUT
#!/bin/bash

# THIS .env FILE IS AUTOGENERATED AT TIME: $(date)
# THIS FILE SHOULD NOT BE CHANGED MANUALLY AND
# SHOULD IGNORED BY '.gitignore'

EOF

for name in $(list); do
    value=$(get $name)
    echo "export $name='$value'" >> $ENV_OUT
    echo "export TF_VAR_$name=\$$value" >> $ENV_OUT
done
