name: donas-server

services:
  front-end:
    platform: linux/amd64
    container_name: donas-front-end
    image: ghcr.io/donasbydonation/front-end:main
    ports:
      - "${APP_WEB_PORT}:${APP_WEB_CONTAINER_PORT}"
    environment:
      - "BACK_END_URL=back-end:${APP_API_CONTAINER_PORT}"
    restart: always
    networks:
      - donas-server
    depends_on:
      - back-end
  back-end:
    platform: linux/amd64
    container_name: donas-back-end
    image: ghcr.io/donasbydonation/back-end:main
    ports:
      - "${APP_API_PORT}:${APP_API_CONTAINER_PORT}"
    environment:
      - "DB_URL=jdbc:${AWS_RDS_ENGINE}://${AWS_RDS_HOST}:${AWS_RDS_PORT}/${AWS_RDS_DBNAME}"
      - "DB_USER=${AWS_RDS_USERNAME}"
      - "DB_PASSWORD=${AWS_RDS_PASSWORD}"
      - "DB_DRIVER=org.${AWS_RDS_ENGINE}.jdbc.Driver"
      - "MAIL_HOST=${APP_API_MAIL_HOST}"
      - "MAIL_PORT=${APP_API_MAIL_PORT}"
      - "MAIL_USERNAME=${APP_API_MAIL_USERNAME}"
      - "MAIL_PASSWORD=${APP_API_MAIL_PASSWORD}"
      - "JWT_SECRET_KEY=${APP_API_JWT_SECRET_KEY}"
      - "JWT_EXPIRATION_MS=${APP_API_JWT_EXPIRATION_MS}"
      - "ADMIN_EXPIRATION_MS=${APP_API_ADMIN_EXPIRATION_MS}"
      - "AWS_ACCESS_KEY=${APP_API_AWS_ACCESS_KEY}"
      - "AWS_SECRET_KEY=${APP_API_AWS_SECRET_KEY}"
      - "AWS_REGION=${APP_API_AWS_REGION}"
      - "AWS_S3_BUCKET=${APP_API_AWS_S3_BUCKET}"
      - "ADMIN_USERNAME=${APP_API_ADMIN_USERNAME}"
      - "ADMIN_PASSWORD=${APP_API_ADMIN_PASSWORD}"
    restart: always
    networks:
      - donas-server
  admin-console:
    platform: linux/amd64
    container_name: donas-admin-console
    image: ghcr.io/donasbydonation/admin-console:main
    ports:
      - "${APP_ADM_PORT}:${APP_ADM_CONTAINER_PORT}"
    environment:
      - "APP_API_HOST=back-end"
      - "APP_API_PORT=${APP_API_CONTAINER_PORT}"
      - "APP_ADM_CONTAINER_PORT=${APP_ADM_CONTAINER_PORT}"
    restart: always
    networks:
      - donas-server
    depends_on:
      - back-end
networks:
  donas-server:
    name: donas-server
