#!/bin/bash

set -e

# - Env
ROOT_DIR=${ROOT_DIR?"ERROR: Required environment variable not set"}
source $ROOT_DIR/.env.config
source $ROOT_DIR/.env.credentials

# - Config
SH_OUT="$ROOT_DIR/aws_asg_user_data.autogen.sh"

# - Dependency
$ROOT_DIR/.helpers.donas.me/docker/docker-compose/export.sh

# - Generate
cat << EOF > $SH_OUT
#!/bin/bash

# THIS .sh FILE IS AUTOGENERATED AT TIME: $(date)
# THIS FILE SHOULD NOT BE CHANGED MANUALLY AND
# SHOULD IGNORED BY '.gitignore'

EOF

cat << EOF >> $SH_OUT
# - Begin
mkdir -pv /etc/donas
cd /etc/donas

EOF

cat << EOF >> $SH_OUT
# - Install Docker
curl -fsSL https://get.docker.com > install_docker.sh
chmod +x install_docker.sh
./install_docker.sh

EOF

cat << EOF >> $SH_OUT
# - Install AWS CodeDeploy agent
apt-get update -qq > /dev/null
DEBIAN_FRONTEND=noninteractive apt-get install -y -qq ruby-full > /dev/null
curl -fsSL https://aws-codedeploy-ap-northeast-2.s3.amazonaws.com/latest/install > install_codedeploy.sh
chmod +x install_codedeploy.sh
./install_codedeploy.sh auto > /tmp/logfile
systemctl enable --now codedeploy-agent.service

EOF

cat << EOF >> $SH_OUT
# - Save 'docker-compose.yaml'
cat << EOF > docker-compose.yaml
EOF
cat $ROOT_DIR/docker-compose.autogen.yaml >> $SH_OUT
echo 'EOF' >> $SH_OUT
echo >> $SH_OUT

cat << EOF >> $SH_OUT
# - Save 'docker-compose.sh'
cat << EOF > docker-compose.sh
#!/bin/bash
docker compose stop
docker compose rm -f
docker compose pull
docker compose up -d
EOF
echo 'EOF' >> $SH_OUT
echo >> $SH_OUT

cat << EOF >> $SH_OUT
# - Start server
chmod +x docker-compose.sh
./docker-compose.sh
EOF

# - Print
base64 $SH_OUT
